spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://ep-blue-fog-awqdh183-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bxjUDmQe3z1i

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.flyway.enabled=true