CREATE TABLE users (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description VARCHAR(500) NOT NULL,
status VARCHAR(100) NOT NULL CHECK (status IN('NEW','IN_PROGRESS','DONE')),
priority VARCHAR(100) NOT NULL CHECK(priority IN('LOW','MEDIUM','HIGH')),
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
user_id BIGINT NOT NULL REFERENCES users(id)
)

CREATE TABLE comments(
id BIGSERIAL PRIMARY KEY,
text VARCHAR(500) NOT NULL ,
author VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
task_id BIGINT NOT NULL REFERENCES tasks(id)
)

